kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-telegrambot
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-telegrambot
    spec:
      containers:
      - name: susi-telegrambot
        image: aliayubkhan/susi_telegrambot:latest
        env:
        - name: token
          value: "387216373:AAFQ0k2pX4JmpoERyUNEIQ5Yk0hW1h0as74"
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-telegrambot
      restartPolicy: Always
